name = "vnghan-internal"
compatibility_date = "2024-08-06"
main = "src/server/index.ts"

[dev]
port = 8080

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[vars]
DATABASE_URL='postgresql://tuan908:ch4PFt5iGABb@ep-wandering-fog-71031792-pooler.ap-southeast-1.aws.neon.tech/vnghan-internal?sslmode=require'